title: TheMCBrothers Blog
title_separator: "-"
name: "TheMCBrothers"
description: >-
  This is the blog of TheMCBrothers.
baseurl: ""
url: "https://blog.themcbrothers.net"
repository: "TheMCBrothers/themcbrothers.github.io"
logo: "/assets/img/logo.png"
breadcrumbs: false
search: true

masthead_title: " "
copyright: "TheMCBrothers"
copyright_url: "https://themcbrothers.net"

social:
  type: "Organization"
  name: "TheMCBrothers"
  links:
    - "https://www.youtube.com/@TheMCBrothers"
    - "https://instagram.com/themcbrothers2016"
    - "https://twitter.com/TheMCBrothers1"

author:
  name: "TheMCBrothers"
  avatar: "/assets/img/avatar/TheMCBrothers.png"
  bio: "Since 2016"
  location: "Switzerland"
  links:
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/@TheMCBrothers"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/TheMCBrothers"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/themcbrothers2016"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/TheMCBrothers"
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/@TheMCBrothers"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/themcbrothers2016"

category_archive:
  type: jekyll-archives
  path: /categories/
tag_archive:
  type: jekyll-archives
  path: /tags/

# TEST ARCHIVES
archives:
  enabled: true
  layout: archive
  permalinks:
    year: /:year/
    month: /:year/:month/
    category: /:category/

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.27.3"
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Outputting
permalink: /:categories/:year/:month/:day/:title:output_ext
timezone: 'Europe/Zurich'
paginate: 5
paginate_path: "/page:num/"

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-archives
  - jekyll-redirect-from
  - jekyll-remote-theme

# Collections
collections:
  posts_uselessmod:
    output: true
    permalink: /:path/
  posts_interiormod:
    output: true
    permalink: /:path/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      show_date: true
      read_time: true
      comments: false
      share: true
      related: true
  # _posts_uselessmod
  - scope:
      path: ""
      type: posts_uselessmod
    values:
      layout: single
      author_profile: true
      show_date: true
      read_time: true
      comments: false
      share: true
      related: true
  # _posts_interiormod
  - scope:
      path: ""
      type: posts_interiormod
    values:
      layout: single
      author_profile: true
      show_date: true
      read_time: true
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single

include:
  - _pages
